name: Code Gating

on:
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./cli

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Cinstrument-coverage
  LLVM_PROFILE_FILE: vscode-%p-%m.profraw

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: ubuntu-latest      
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::201893381538:role/GitHubRole
          role-session-name: GitHubActionsSession
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "cli -> target"
      - name: Add llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - name: Build + Test
        run: |
          cargo build
          cargo test --all-features
      - name: Collect code coverage
        run: |
          wget https://github.com/mozilla/grcov/releases/download/v0.8.18/grcov-x86_64-unknown-linux-gnu.tar.bz2
          tar -xvjf grcov-x86_64-unknown-linux-gnu.tar.bz2
          ./grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore-not-existing -o ./
      - run: ls -l && pwd
      - uses: 5monkeys/cobertura-action@master
        with:
          path: cli/cobertura.xml
          minimum_coverage: 75
      - name: Lint via clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path=cli/Cargo.toml
   
    
